### ISSUE TITLE
Function.StorageServiceClient._normalizeError 

### ISSUE THREAD

**Issue by monaka** [mike-goodwin/connect-azuretables#5]
I tried to use your product and I got an error like below.
The stack trace is similar to #4. But in my case, I just open my apps (not session.destroy()).
I found `ConnectAzureTablesSessions` in my table after. So the authentication will be succeeded.

* express@4.15.2
* express-session@1.15.2
* connect-azuretables@1.0.17
* azure-storage@2.0.0

```
Error
    at Function.StorageServiceClient._normalizeError (/app/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1174:23)
    at Object.StorageServiceClient._processResponse (/app/node_modules/azure-storage/lib/common/services/storageserviceclient.js:729:50)
    at Request.processResponseCallback [as _callback] (/app/node_modules/azure-storage/lib/common/services/storageserviceclient.js:310:37)
    at Request.self.callback (/app/node_modules/azure-storage/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/app/node_modules/azure-storage/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/app/node_modules/azure-storage/node_modules/request/request.js:965:12)
```

**Comment by mike-goodwin** [comment]
Would you be able to post some code to help me figure out where the error is happening? I can't reproduce so it's hard to do anything about it...

**Comment by monaka** [comment]
I put the whole code https://gist.github.com/monaka/d432554db057045957e02a7e3538a73d .
Some security info was modified.
I know it should be simplified by myself before I send code. Just for now.
And can I provide some more information? Debug log flags or something available?

My application is run on [Deis Workflow](http://https://deis.com/) / K8s 1.6 / Azure VM D2_v2.
The instance and the storage account are located on same JapanEast region.
So it' hard to suspect it is caused by network issues, IMO.

**Comment by mike-goodwin** [comment]
Thank you. I looked at the code and can't see anything obviously wrong. I notice that you are not doing any logging in the library:

`app.use(session({
  store: AzureTablesStoreFactory.create(),
  secret: 'cat yay! yay!'
//  resave: false,
//  saveUninitialized: false,
//  maxAge: 3600000
}));`

Please can you pass a logger in as described in the readme:

https://github.com/mike-goodwin/connect-azuretables#logging

And share the output.

**Comment by mike-goodwin** [comment]
Also, it would be great if you could post minimal code reproducing the issue (for example, using `'passport-local`' instead of Azure AD) so I can reproduce it easily.

**Comment by GaneshSinghPapola** [comment]
You can make a temporary solution here: goto /your-application/node-modules/connect-azuretables/lib/ , open connect-azuretables.js and replace the following code there at AzureTablesStore.prototype.get function, line no 121 ::
  

      AzureTablesStore.prototype.get = function(sid, fn, retry) {
        var store = this;
        var cleanSid = sanitize(sid);
        
        if (!fn) {
            fn = noop;
        }
        //this.log('connect-azuretables called GET ' + sid);
        try{
            store.tableService.retrieveEntity(store.table, cleanSid, cleanSid, function(error, result) {

                if (error && error.statusCode == 404 && !retry) {
                    store.get(sid, fn, true);
                } else {
                    var error = null;
                    return error || !result ? fn(error) : fn(null, JSON.parse(result.data._));
                }
            });
        }
        catch(error){
            console.log(error);
        }

    };

**Comment by monaka** [comment]
@GaneshSinghPapola Thanks for you information. I'm working the another task now. So I'll try your code a few days later.

**Comment by GaneshSinghPapola** [comment]
@monaka  :+1:

**Comment by monaka** [comment]
I tried  the new code and still this issue isn't fixed on my environment. I'm inspecting code now.

**Comment by monaka** [comment]
I'm close to the root cause.
In my case, my web browser held session (cookie?) and there is no session key in my AzureTable. It's not by timing issues.

Referring to [API reference of expressjs/session](https://github.com/expressjs/session#storegetsid-callback), it should return `null` or `undefined` if session was not stored.
I'll send the pull request later.

**Comment by GaneshSinghPapola** [comment]
ok  @monaka

**Comment by monaka** [comment]
Sorry for my delay.

**Comment by mike-goodwin** [comment]
Thanks for the contribution and apologies for the delay in merging - i've had to take an enforced break from the project for a while.
